Remove trim on result of exec command
steelbrain/node-ssh pull request #475
Opened 2024-04-18 04:59 UTC by kimbob13

Hello,
I'm using this library to execute command on remote host,
and I want the result to be exactly same as what executed locally.

I think trimming process is a choice of user of library side, not what the library should perform.
Therefore, this PR removes trim method on stdout and stderr results.

2024-04-18 05:02 UTC, steelbrain requested changes
Hi @kimbob13! Thanks for the PR. Would you be interesting in adding a new `noTrim: true | false` option instead?

This allows us to cater to most people's needs, as they don't need the extra newline at the end, but for the people who need it, they can turn on the option instead.

2024-04-18 05:03 UTC, kimbob13 commented
Thanks for the suggestions! I'll add option instead.

2024-04-18 05:14 UTC, kimbob13 commented
@steelbrain I've changed to option approach and force pushed.

2024-04-18 05:16 UTC, steelbrain approved these changes
Minor change and then we're good to go!

2024-04-18 05:16 UTC, steelbrain commented on src/index.ts
> +          if (options.noTrim === false) {
```suggestion
          if (options.noTrim !== true) {
```

2024-04-18 05:54 UTC, kimbob13 commented
Warmly reminder, commit added!

2024-04-18 05:56 UTC, steelbrain commented
Thank you for working on this! I’ll add some tests and make some doc changes before releasing. (Also happy to accept PRs for them )

2024-04-18 05:56 UTC, merged

2024-04-20 17:25 UTC, steelbrain commented
Released in https://github.com/steelbrain/node-ssh/releases/tag/v13.2.0